version: '3.8'

services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    image: leapcreate/wordpress
    user: '${UID}:${GID}'
    ports:
      - '80:80'
      - '443:443'
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX}
      WORDPRESS_DEBUG: ${DEBUG}
    volumes:
      - ./public:/var/www/html

  composer:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    image: leapcreate/composer
    container_name: composer

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      UPLOAD_LIMIT: 50M

volumes:
  db_data: {}
